//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Desktop.Plugins.HisStudent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string maSinhVien { get; set; }
        public string HovaTen { get; set; }
        public string doiTuong { get; set; }
        public string hoNgheo { get; set; }
        public string thanhTich { get; set; }
        public string ghiChu { get; set; }
    }
}
